version: '3'
services:
   db:
      image: "mysql:9.1"
      environment:
         - MYSQL_ROOT_PASSWORD=root
         - MYSQL_DATABASE=hamster
         - MYSQL_USER=hamster
         - MYSQL_PASSWORD=secret
         - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      restart: always
      healthcheck:
         test: '/usr/bin/mysql --user=hamster --password=secret --execute "SHOW DATABASES;"'
         interval: 3s
         timeout: 1s
         retries: 5
   web:
      image: "clivern_hamster:3.1.0"
      build: .
      command: './hamster'
      ports:
         - "8080:8080"
      depends_on:
         - db
      volumes:
         - './var:/go/src/github.com/clivern/hamster/var'
      restart: always
      environment:
         - GithubToken=YourTokenHere
         - GithubWebhookSecret=YourSecretHere
         - RepositoryAuthor=Clivern
         - RepositoryName=Hamster
         - AppMode=prod
         - AppPort=8080
         - AppLogLevel=info
         - GithubAppClientID=ValueHere
         - GithubAppRedirectURI=ValueHere
         - GithubAppAllowSignup=true
         - GithubAppScope=ValueHere
         - GithubAppClientSecret=ValueHere
         - AppDomain=example.com