version: '3'
services:
  web:
    image: "hamster:latest"
    ports:
      - "8080:8080"
    environment:
      - DB_HOSTNAME=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_DATABASE=hamster
      - DB_CHARSET=utf8mb4
      - DB_COLLATION=utf8mb4_unicode_ci

  db:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes